### ISSUE TITLE
Ads country-specific?

### ISSUE THREAD

**Issue by T-IOOO** [kboghdady/youTube_ads_4_pi-hole#58] opened 2020-07-09 14:05 UTC
I have tried this list for about a week now. Hard to say whether it’s working or not but one thing is for sure, the only ads I am seeing right now is country-specific. I only see ads in my native language. Just want to let you know. Maybe a domain change will do it?

**Comment by MarioGK** [comment] 2020-07-12 16:45
Some people(me included) have noticed that this list works best in the US only, we are waiting and expecting the Author of this script release a way we can make lists for other countries lists as well.

**Comment by T-IOOO** [comment] 2020-07-12 16:58
That would be great, it would be awesome if pi-hole or another project could grab and store links automatically in this list while watching clips on youtube.

**Comment by Stephen988** [comment] 2020-07-22 19:46
After some day of testing this list don't block any ads for my country: Italy, hope in near future.

**Comment by kboghdady** [comment] 2020-07-24 16:45
Duplicate of #32

**Closed by kboghdady** 2020-07-24 16:45 UTC
