### ISSUE TITLE
Youtube is also blocked along with ads

### ISSUE THREAD

**Issue by alvaroledesma** [kboghdady/youTube_ads_4_pi-hole#40] opened 2020-03-02 02:16 UTC
I can't access Youtube along with the ads. I believe DNS is blocking youtube as well as ads

**Comment by kboghdady** [comment] 2020-03-02 02:29
could you please run ```pihole -t``` while you playing youtube and it is blocked

**Comment by alvaroledesma** [comment] 2020-03-02 02:33
Yes, I ran it and see all the link being redirected to 0.0.0.0

**Comment by kboghdady** [comment] 2020-03-02 02:36
I need the logs to see it. my secript doesn't block youtube itself.

**Comment by kboghdady** [comment] 2020-03-02 03:10
Duplicate of #20

**Comment by kboghdady** [comment] 2020-03-04 20:43
I am working on it today and updating the list.
if you are using the youtube.sh script make sure to remove both :
rm /etc/pihole/black*
if you are using the gravity list make sure to update it

**Closed by kboghdady** 2020-03-04 20:43 UTC
