### ISSUE TITLE
[question] How did you've compiled the list of servers?

### ISSUE THREAD

**Issue by eladkarako** [kboghdady/youTube_ads_4_pi-hole#70] opened 2020-09-01 13:29 UTC
I'm pretty sure all those servers are capable of serving both ads and regular-content (correct me if I'm wrong),  

as far as I could ever figure out,  
this is the minimal way of blocking ads,  
https://gist.github.com/eladkarako/7ee77942acc066f930de0268c387239e#file-block-youtube-ads-md
and some of the ads (in-video banners) are unavoidable since they are served by the same servers that serves regular video-thumbnails,  

Those few-ads are hide-able though, but this requires desktop-solution such as uBlock-origin and not related to pi-hole (again, correct me if this is possible).

would appreciate feedback to improve <a href="https://gist.github.com/eladkarako/7ee77942acc066f930de0268c387239e#file-block-youtube-ads-md">it</a>...

**Comment by kboghdady** [comment] 2020-09-23 04:51
Duplicate of #Duplicate of #32

**Closed by kboghdady** 2020-09-23 04:51 UTC

**Comment by eladkarako** [comment] 2020-09-23 09:57
May I suggest you'll pin of those, if it is that of a common question.
