### ISSUE TITLE
how did you extract this urls 

### ISSUE THREAD

**Issue by DevSaumyadip** [kboghdady/youTube_ads_4_pi-hole#74] opened 2020-09-09 09:21 UTC
https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/youtubelist.txt

if you please enlight us, how did you manage to get this urs, so that we can also contribute to it and update the list because google throw ads region-specific . and I can update the ads thrown in my region.

**Comment by kboghdady** [comment] 2020-09-13 16:39
Duplicate of #32

**Closed by kboghdady** 2020-09-13 16:39 UTC
