### ISSUE TITLE
Video won't to start

### ISSUE THREAD

**Issue by xziBBerx** [kboghdady/youTube_ads_4_pi-hole#41] opened 2020-03-06 21:01 UTC
Hey, is it possible that the video no longer shows advertisements but does not start the video? It's stuck in an endless loop. It seems to me a lot

**Comment by kboghdady** [comment] 2020-03-06 21:13
run the pihole -r while the video is stuck and send me the logs

**Comment by xziBBerx** [comment] 2020-03-06 21:22
Here is a snippet of the pihole -t

```
Mar  6 22:21:43 dnsmasq[30407]: query[AAAA] r3---sn-4g5e6nz7.googlevideo.com from 192.168.178.1
Mar  6 22:21:43 dnsmasq[30407]: /etc/pihole/black.list r3---sn-4g5e6nz7.googlevideo.com is 0.0.0.0
```

**Comment by xziBBerx** [comment] 2020-03-06 21:24
`Mar  6 22:23:51 dnsmasq[30407]: query[AAAA] r3---sn-4g5ednld.googlevideo.com from 192.168.178.1
Mar  6 22:23:51 dnsmasq[30407]: /etc/pihole/black.list r3---sn-4g5ednld.googlevideo.com is 0.0.0.0`

**Comment by xziBBerx** [comment] 2020-03-06 22:01
`r6---sn-4g5ednee.googlevideo.com
r4---sn-4g5e6nsd.googlevideo.com
r4---sn-h0jeened.googlevideo.com
r6---sn-4g5edne7.googlevideo.com
r1---sn-4g5e6nzl.googlevideo.com
`

**Comment by xziBBerx** [comment] 2020-03-07 07:49
`r5---sn-4g5e6nle.googlevideo.com` also stuck

**Comment by xziBBerx** [comment] 2020-03-07 07:59
it looks very hard to filter all links that stuck. I thunk they get a daily random link
`r3---sn-4g5e6ns6.googlevideo.com
r3---sn-4g5ednsr.googlevideo.com
`

**Comment by kboghdady** [comment] 2020-04-29 18:19
I will implement addon to ignore list we discover it blocks the video. 
We should see this shortly :) 
thank you

**Comment by jrwren** [comment] 2020-05-04 14:43
r2---sn-vgqsrn7d...

also stuck.

**Comment by truthsword** [comment] 2020-05-13 18:01
I'm certain this is a daunting endeavor. As much as YT ads annoy me, I am more frustrated at the "stuck" videos, and page refreshes I must go through to play a video. I've had to whitelist many servers to regain YT usability. I believe Google has won this battle. For now, I'm taking a 6-month hiatus from this filter. Thanks for the work you've put into this.

**Comment by polymathuk** [comment] 2020-06-11 15:47
Same problem with today's blocklist. Is there a fix for this yet?

**Comment by kboghdady** [comment] 2020-06-11 15:49
I will work on that this weekend and see what I can do to fix that.

**Comment by polymathuk** [comment] 2020-06-11 15:58
Hmm. I just ran pihole -r and the problem has stopped. In fact the videos now load faster than ever since there are far fewer ad DNS requests getting through :-)

**Comment by kboghdady** [comment] 2020-06-25 19:50
I removed a lot of DNS that goes into loop please run these commands to update your list
pihole -g ; sudo pihole restartdns

**Comment by kboghdady** [comment] 2020-06-25 19:51
Duplicate of #49

**Closed by kboghdady** 2020-06-25 19:51 UTC
